/**
 * BookStore APIs
 * BookStore APIs exposed from a Java EE back-end to an Angular front-end
 *
 * OpenAPI spec version: 1.0.0
 * Contact: raffaeu@gmail.com
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


/**
 * Book resource representation
 */
export interface Book {
    /**
     * The Unique Identifier
     */
    id?: number;
    /**
     * The Title of the Book
     */
    title: string;
    /**
     * The Description of the Book
     */
    description?: string;
    /**
     * The Price of the Book per unit
     */
    price?: number;
    /**
     * The ISBN Code of the Book
     */
    isbn?: string;
    /**
     * The Date of Release
     */
    publicationDate?: Date;
    /**
     * The Number of Pages available
     */
    nbOfPages?: number;
    /**
     * The URL of the Front Page
     */
    imageUrl?: string;
    /**
     * The Language used in the Book
     */
    language?: Book.LanguageEnum;
}
export namespace Book {
    export type LanguageEnum = 'ENGLISH' | 'FRENCH' | 'SPANISH' | 'PORTUGUESE' | 'ITALIAN' | 'FINISH' | 'GERMAN' | 'DEUTSCH' | 'RUSSIAN';
    export const LanguageEnum = {
        ENGLISH: 'ENGLISH' as LanguageEnum,
        FRENCH: 'FRENCH' as LanguageEnum,
        SPANISH: 'SPANISH' as LanguageEnum,
        PORTUGUESE: 'PORTUGUESE' as LanguageEnum,
        ITALIAN: 'ITALIAN' as LanguageEnum,
        FINISH: 'FINISH' as LanguageEnum,
        GERMAN: 'GERMAN' as LanguageEnum,
        DEUTSCH: 'DEUTSCH' as LanguageEnum,
        RUSSIAN: 'RUSSIAN' as LanguageEnum
    }
}
